### PR TITLE
Running your first ganga job lesson updated

### PR DESCRIPTION
**Pull request by vlisovsk**
The script provided in this lesson is not working (job always fails, to be more precise - fails to read the dataset) if several non-evident actions are not taken in advance.
So, instructions updated.

Request @lcapriot in the thread to check if this is fine for you?

Additional technical comment: since the list of LFNs is enormous (700+), for the purpose of the lesson we may comment most of them and leave only ~25 first, so that people do not have to wait several hours until job finishes.
Splitting by subjobs solves this issue, however, it is a subject of one the following lessons.

### CODE REVIEW

**Comment by vlisovsk** [comment]
By the way, I didn't quite get why do we have these lines about FileCatalog in the [file](https://github.com/lhcb/starterkit-lessons/blob/master/first-analysis-steps/data/MC_2016_27163002_Beam6500GeV2016MagDownNu1.625nsPythia8_Sim09b_Trig0x6138160F_Reco16_Turbo03_Stripping28NoPrescalingFlagged_ALLSTREAMS.DST.py) proposed in the 
[finding data in the bkk lesson](https://lhcb.github.io/starterkit-lessons/first-analysis-steps/bookkeeping.html), at the line 'A copy of the file we just downloaded is available here.'?

**Comment by lcapriot** [comment]
Actually there is a problem with using only a fraction of the jobs in the list if running with Dirac() backend: one would ideally need to make sure that all the files have replicas on the same node, otherwise the job will fail with `extraInfo = No candidate sites available`. So for the purpose of this exercise we need to run on a single file (by deleting/commenting all the others).

**Comment by vlisovsk** [comment]
@lcapriot did you check it works fine with only one LFN?

**Comment by vlisovsk** [comment]
Well, I will answer by my question myself - it seems it does

**Comment by lcapriot** [comment]
Sorry for the late reply - yes it does, as you have already seen I suppose.

**Pull request merged**
