### PR TITLE
Changed wget link to reverse.py script. Was not working.

### PR DESCRIPTION
**Pull request by lucapescatore88**
Changed wget link to reverse.py script. Was not working.

### CODE REVIEW

**Comment by apuignav** [comment]
I don't think this is correct. It downloads the webpage, not the document.

I believe the correct link is [https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/01-managing-files-with-ganga/reverse.py](https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/01-managing-files-with-ganga/reverse.py).

**Comment by lucapescatore88** [comment]
Ah yes indeed. It downloads reverse.py hit it has html into it. So what's the proper way? The link there was before gives me error 404.

**Comment by apuignav** [comment]
I think the link to the raw file: https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/01-managing-files-with-ganga/reverse.py

**Comment by lucapescatore88** [comment]
Ok yes indeed this works. I'll re-change it. How do you get this raw link?

**Comment by apuignav** [comment]
Follow your link, click the 'Raw' button :-)

**Pull request merged**
