### PR TITLE
Fix broken links and remove reference to ganga version

### PR DESCRIPTION
**Pull request by chrisburr**
Fixes a bunch of broken links and removes the mention of the specific ganga version.

### CODE REVIEW

**Comment by vlisovsk** [comment]
I know this is a minor thing, but every ganga prompt in this lesson starts from `Version: 6.5.1`. Should this be updated to `Version: 7.0.2` which is the current default?

**Comment by chrisburr** [comment]
I'm not sure as I think we shouldn't need to update the lesson for every point release provided it still works.

What do you think about changing it to `X.Y.Z` and mentioning "you should always use the default unless you have a specific reason not to"?

**Comment by vlisovsk** [comment]
Unrelated comment: could you please do a quick language improvement throughout the lesson, if possible? There are quite some grammar mistakes and typos.
Some prominent examples:
>Part of Ganga's power come -> Part of Ganga's power comes
>your dropped into a prompt -> you are dropped into a prompt

**Comment by chrisburr** [comment]
Will do, I'll look at it later today and make a separate pull request.

**Comment by vlisovsk** [comment]
Well, then merged!
Thanks!

**Pull request merged**
