### PR TITLE
Update the LOKI lesson

### LINKED ISSUE #162: Update Loki lesson
In the new MC we use, the first candidate is a D*0+ instead of D*0-
Update as well the example with CHILD

### PR DESCRIPTION
**Pull request by vlisovsk**
- Closes #162 (updated charge signs)
- Removed latex from the challenge box to make it look better

### CODE REVIEW

**Comment by vbellee** [comment]
- Looks good
- Thanks for removing latex, so that we can see what's in the box

**Comment by vlisovsk** [comment]
Do you know why Travis takes so much time? I think everything is ok [here](https://travis-ci.org/lhcb/starterkit-lessons/pull_requests)

**Comment by vbellee** [comment]
No idea...

**Comment by chrisburr** [comment]
Fixed :)

**Pull request merged**
