### PR TITLE
WIP: Sebastian's recommended changes as well as lb-conda

### PR DESCRIPTION
**Pull request by AndyLHCb**

### CODE REVIEW

**Comment by seneubert** [comment]
Thanks for including this!
Please add the usege of the reports feature. It works this way:

1. you run the snakemake workflow as normal
2. you run snakemake a second time, now with the `--report` option. This will create the html output.

See documentation for details  

Also please include some example screenshots. If you don't have any, please push me until I give you some :)

Thanks!

**Comment by AndyLHCb** [comment]
@seneubert, is this looking better to you? For now I've put in the reports as screenshots but I'm hoping that once I have more time I'll be able to make an example report be hosted as a separate html document

**Comment by seneubert** [comment]
Looks  good. The only thing I'd change back is, that the report macro should refer to the graphics file (e.g. output.pdf).
You had it that way originally but for some reason changed to output.root.
ROOT files can also be included in the report, but in that case of course no thumbnail/preview will be generated.

**Review by seneubert — APPROVED** [review]
Excellent. Looks great. Thanks a lot for this!

**Pull request merged**
