### PR TITLE
Bump DaVinci version to v45r5

### PR DESCRIPTION
**Pull request by alexpearce**
We encourage using the latest possible version in the lessons, so let's do it 😄

### CODE REVIEW

**Comment by vlisovsk** [comment]
Is any code in the lessons giving [this](https://groups.cern.ch/group/lhcb-davinci/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Flhcb%2Ddavinci%2FLists%2FArchive%2FERROR%20putStatusOnTES%28%29%20RawBankReadoutStatus%20not%20created%20for%20this%20event%2C%20not%20putting%20it%20on%20TES&FolderCTID=0x01200200B795ECDBD8943F4E90E5F02A017196C9) error flooding the log with this DaVinci version? It would be awkward if this happens.

**Comment by alexpearce** [comment]
Good point, I'll check.

**Comment by alexpearce** [comment]
The minimal DaVinci, DTF, and LoKi options run OK.

But now I'm worried because it might be triggered by something we do later on, or something a teacher tries to do on the fly. That would be very confusing 😞 So I'm on the fence about merging.

**Comment by vlisovsk** [comment]
Also note that if this were merged, we need to update the platform in ganga lessons as v45r5 does not run on gcc8.

**Comment by vlisovsk** [comment]
We can now jump to DaVinci v45r6 where the error message is silenced.

**Comment by alexpearce** [comment]
Indeed! I've updated it now, along with bumping the default platform to match what's available for v45r6.

**Comment by eduardo-rodrigues** [comment]
Is this not obsoleted by the fact that MR https://github.com/lhcb/starterkit-lessons/pull/272 (possibly other parts?) updated to DaVinci v45r8?

**Comment by vlukashenko** [comment]
Is superseded by https://github.com/lhcb/starterkit-lessons/pull/277

**Pull request closed without merging**
