### PR TITLE
Adding Run 3 data flow lesson 

### PR DESCRIPTION
**Pull request by lukascalle**

### CODE REVIEW

**Comment by lukascalle** [comment]
@cagapopocagapopo and me added a Run 3 data flow lesson for the corresponding starterkit lesson this year. When I opened a pull request, I was guided to this 3 year old pull request I was once did to add one line to the Ganga lesson :)

**Comment by vlukashenko** [comment]
Hi, Lukas! Thanks for the lesson. Do I understand correctly you want to point to the Moore examples from here? If so where? Or should we add a separate wrapper?

**Review by vlukashenko — COMMENTED** [review]
Hi, Lukas! I hope you now can see it

**Comment by lukascalle** [comment]
> Hi, Lukas! Thanks for the lesson. Do I understand correctly you want to point to the Moore examples from here? If so where? Or should we add a separate wrapper?

I tried to make the connection to the Moore docs a bit more explicit. If you feel it needs more wrapping, feel free to add it.

**Pull request merged**
