### PR TITLE
small updates/corrections

### PR DESCRIPTION
**Pull request by goi42**

### CODE REVIEW

**Comment by alexpearce** [comment]
I guess your editor is configured specifically, but it's a little annoying having changes just for the line width. This is partly our fault, we should provide an [edtior config file](http://editorconfig.org/) or something, but while we don't have that I think these sorts of changes just muddy the `git blame` history.

For the formatting issue: is it possible to use LaTeX markup here instead? e.g. `$$D^{*+}$$`

**Comment by apuignav** [comment]
@alexpearce We should provide a style guide? I would say one sentence one line...

**Comment by alexpearce** [comment]
Opened #79 for discussion on style guides/editor configs.

**Comment by goi42** [comment]
@alexpearce Apologies for the small change--I opened it up just to fix the the D* problem.

I corrected the line lengths to be more in-line with the rest of the repository--I was under the impression that shorter line lengths made for easier reading of the changes as there will not be such long lines of text marked as different. I can roll back the line-length changes if you'd like.

**Comment by apuignav** [comment]
Please do, I think we need to fix all at once depending on what we decide in #79.

However, thanks a lot for the effort!

**Pull request closed without merging**
