### PR TITLE
link to CERN-hosted event type finder

### PR DESCRIPTION
**Pull request by abmorris**

### CODE REVIEW

**Comment by chrisburr** [comment]
Thanks! :cake:

**Comment by eduardo-rodrigues** [comment]
Hi @abmorris, maybe you would also like to add a definition + this link to the LHCb glossary? In general I would like to see the glossary being used in the StarterKit. I'm pretty sure I wrote an "issue" about that in the past ...

**Comment by abmorris** [comment]
OK, I will add definitions for "Event type" and "DecFile".

Actually there's a lot of simulation terminology I don't see in there. I'll make an issue to not forget

**Comment by eduardo-rodrigues** [comment]
Thanks @abmorris! Indeed there are many things still missing in the glossary.

**Pull request merged**
