### PR TITLE
Links to raw files were still pointing to merged snakemake branch

### PR DESCRIPTION
**Pull request by lucapescatore88**
Links to raw files were still pointing to merged snakemake branch

### CODE REVIEW

**Comment by chrisburr** [comment]
I've edited this to use the raw URLs rather than the raw urls parameter, i.e.
```
https://github.com/lhcb/starterkit-lessons/raw/master/second-analysis-steps/code/snakemake/tutorial.tar
```
instead of:
```
https://github.com/lhcb/starterkit-lessons/blob/master/second-analysis-steps/code/snakemake/tutorial.tar?raw=true
```
The advantage is that if you use wget the filename is `tutorial.tar` instead of `tutorial.tar?raw=true`.

**Comment by lucapescatore88** [comment]
Actually I tried it and it did not download the correct file. Did you try it?

**Comment by lucapescatore88** [comment]
I just re-tried. Only with "?raw=true" the real tar is downloaded. Maybe there is an other way but not putting the raw=true does not work.

**Comment by chrisburr** [comment]
Really?
If I use curl and compare the hashes they are the same:
```
$ curl -L https://github.com/lhcb/starterkit-lessons/blob/master/second-analysis-steps/code/snakemake/tutorial.tar\?raw\=true | gmd5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169    0   169    0     0    169      0 --:--:-- --:--:-- --:--:--   239
100   180  100   180    0     0    180      0  0:00:01 --:--:--  0:00:01  175k
100  3070  100  3070    0     0   3070      0  0:00:01  0:00:01 --:--:--  3070
bac1bcc45b6b2ce8b758df1d56515087  -
$ curl -L https://github.com/lhcb/starterkit-lessons/raw/master/second-analysis-steps/code/snakemake/tutorial.tar | gmd5sum           ✓  10697  23:10:50
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   180  100   180    0     0    180      0  0:00:01 --:--:--  0:00:01   277
100  3070  100  3070    0     0   3070      0  0:00:01 --:--:--  0:00:01  3070
bac1bcc45b6b2ce8b758df1d56515087  -
```
And if I use wget then tar the same files are extracted:
```
$ wget https://github.com/lhcb/starterkit-lessons/raw/master/second-analysis-steps/code/snakemake/tutorial.tar
--2018-05-09 23:12:34--  https://github.com/lhcb/starterkit-lessons/raw/master/second-analysis-steps/code/snakemake/tutorial.tar
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/snakemake/tutorial.tar [following]
--2018-05-09 23:12:34--  https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/snakemake/tutorial.tar
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3070 (3.0K) [application/octet-stream]
Saving to: ‘tutorial.tar’

tutorial.tar                                  100%[==============================================================================================>]   3.00K  --.-KB/s    in 0s

2018-05-09 23:12:35 (9.82 MB/s) - ‘tutorial.tar’ saved [3070/3070]

$ tar xvf tutorial.tar
x tutorial/
x tutorial/._.DS_Store
x tutorial/.DS_Store
x tutorial/simple_solution/
x tutorial/more_complete_solution/
x tutorial/inputs/
x tutorial/inputs/addresses.txt
x tutorial/inputs/phones.txt
x tutorial/more_complete_solution/._merge.py
x tutorial/more_complete_solution/merge.py
x tutorial/more_complete_solution/._cfg.yaml
x tutorial/more_complete_solution/cfg.yaml
x tutorial/more_complete_solution/._get.snake
x tutorial/more_complete_solution/get.snake
x tutorial/more_complete_solution/._Snakefile
x tutorial/more_complete_solution/Snakefile
x tutorial/more_complete_solution/._merge.snake
x tutorial/more_complete_solution/merge.snake
x tutorial/simple_solution/._.DS_Store
x tutorial/simple_solution/.DS_Store
x tutorial/simple_solution/And a more complete solution/
x tutorial/simple_solution/._Snakefile
x tutorial/simple_solution/Snakefile
x tutorial/simple_solution/inputs/
x tutorial/simple_solution/inputs/addresses.txt
x tutorial/simple_solution/inputs/phones.txt
x tutorial/simple_solution/And a more complete solution/._merge.py
x tutorial/simple_solution/And a more complete solution/merge.py
x tutorial/simple_solution/And a more complete solution/._cfg.yaml
x tutorial/simple_solution/And a more complete solution/cfg.yaml
x tutorial/simple_solution/And a more complete solution/._get.snake
x tutorial/simple_solution/And a more complete solution/get.snake
x tutorial/simple_solution/And a more complete solution/._Snakefile
x tutorial/simple_solution/And a more complete solution/Snakefile
x tutorial/simple_solution/And a more complete solution/._merge.snake
x tutorial/simple_solution/And a more complete solution/merge.snake
$ rm -rf tutorial*
$ wget -L https://github.com/lhcb/starterkit-lessons/blob/master/second-analysis-steps/code/snakemake/tutorial.tar\?raw\=true
--2018-05-09 23:12:59--  https://github.com/lhcb/starterkit-lessons/blob/master/second-analysis-steps/code/snakemake/tutorial.tar?raw=true
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/lhcb/starterkit-lessons/raw/master/second-analysis-steps/code/snakemake/tutorial.tar [following]
--2018-05-09 23:12:59--  https://github.com/lhcb/starterkit-lessons/raw/master/second-analysis-steps/code/snakemake/tutorial.tar
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/snakemake/tutorial.tar [following]
--2018-05-09 23:13:00--  https://raw.githubusercontent.com/lhcb/starterkit-lessons/master/second-analysis-steps/code/snakemake/tutorial.tar
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3070 (3.0K) [application/octet-stream]
Saving to: ‘tutorial.tar?raw=true’

tutorial.tar?raw=true                         100%[==============================================================================================>]   3.00K  --.-KB/s    in 0s

2018-05-09 23:13:00 (10.8 MB/s) - ‘tutorial.tar?raw=true’ saved [3070/3070]

$ tar xvf tutorial.tar\?raw=true 
x tutorial/
x tutorial/._.DS_Store
x tutorial/.DS_Store
x tutorial/simple_solution/
x tutorial/more_complete_solution/
x tutorial/inputs/
x tutorial/inputs/addresses.txt
x tutorial/inputs/phones.txt
x tutorial/more_complete_solution/._merge.py
x tutorial/more_complete_solution/merge.py
x tutorial/more_complete_solution/._cfg.yaml
x tutorial/more_complete_solution/cfg.yaml
x tutorial/more_complete_solution/._get.snake
x tutorial/more_complete_solution/get.snake
x tutorial/more_complete_solution/._Snakefile
x tutorial/more_complete_solution/Snakefile
x tutorial/more_complete_solution/._merge.snake
x tutorial/more_complete_solution/merge.snake
x tutorial/simple_solution/._.DS_Store
x tutorial/simple_solution/.DS_Store
x tutorial/simple_solution/And a more complete solution/
x tutorial/simple_solution/._Snakefile
x tutorial/simple_solution/Snakefile
x tutorial/simple_solution/inputs/
x tutorial/simple_solution/inputs/addresses.txt
x tutorial/simple_solution/inputs/phones.txt
x tutorial/simple_solution/And a more complete solution/._merge.py
x tutorial/simple_solution/And a more complete solution/merge.py
x tutorial/simple_solution/And a more complete solution/._cfg.yaml
x tutorial/simple_solution/And a more complete solution/cfg.yaml
x tutorial/simple_solution/And a more complete solution/._get.snake
x tutorial/simple_solution/And a more complete solution/get.snake
x tutorial/simple_solution/And a more complete solution/._Snakefile
x tutorial/simple_solution/And a more complete solution/Snakefile
x tutorial/simple_solution/And a more complete solution/._merge.snake
x tutorial/simple_solution/And a more complete solution/merge.snake
```

**Pull request merged**
