### PR TITLE
Update trigger intro

### PR DESCRIPTION
**Pull request by saschastahl**
I have updated the instructions to be more inline with running on recent data. Please do not merge yet, I have to make sure that PrConfig gets released so that we can pick up one file form the TestFileDB in the tutorial.

### CODE REVIEW

**Comment by chrisburr** [comment]
[Has PrConfig been released or is it a different version?](https://sft.its.cern.ch/jira/projects/LHCBDEP/issues/LHCBDEP-3784?filter=allissues)

**Comment by saschastahl** [comment]
That should be it, I am testing now if the options I wrote down actually work.

**Comment by saschastahl** [comment]
Thinks look good, I think we can merge.

**Comment by chrisburr** [comment]
Perfect, thanks for this 👍

**Pull request merged**
