### PR TITLE
Add some introduction to the loki session

### PR DESCRIPTION
**Pull request by saschastahl**
The LoKi lesson starts quite abrupt and I think none of the lessons before shows a LoKi functor. I hope these few introductory words make it easier.

### CODE REVIEW

**Comment by vlisovsk** [comment]
Thanks for this!

There is one another place where a bit of context feels missing. 
The sentence "This can be done calling the function momentum() for our candidate ..." suddenly introduces the `momentum()` function, but we did not talk about the meaning of this. Should Gaudi framework be mentioned here?. 
Ideally, I would also love to see a sentence about what kind of information is stored in the DST and what LOKI does behind the scenes.

**Comment by saschastahl** [comment]
I added an extra sentence trying to address the issue with momentum. It might be too technical and hopefully it is correct.

I am not sure how to address the other issues. What do you mean by what LoKi does behind the scenes?

**Comment by vlisovsk** [comment]
Thanks, the change look good to me already. I corrected a couple of other things, apologies for hijacking your MR.

**Comment by vlisovsk** [comment]
should we merge this before the lesson (= now?)

**Comment by saschastahl** [comment]
Thanks for quickly merging. I hadn't realized that and actually did not refresh my browser :(.

**Pull request merged**
